version: '3.8'

services:
  sample-service:
    build:
      context: .
      dockerfile: src/sample_service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Tell the app where the collector is.
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - zebra-network
    depends_on:
      - otel-collector

  zebra-observer:
    build:
      context: .
      dockerfile: src/zebra_orchestrator/Dockerfile
    ports:
      - "9090:9090"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_SUPABASE_ANON_KEY=${VITE_SUPABASE_SUPABASE_ANON_KEY}
    networks:
      - zebra-network
    depends_on:
      - otel-collector
    volumes:
      - ./pr_proposals:/app/pr_proposals

  zebra-causal-worker:
    build:
      context: .
      dockerfile: src/zebra_orchestrator/Dockerfile
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_SUPABASE_ANON_KEY=${VITE_SUPABASE_SUPABASE_ANON_KEY}
    networks:
      - zebra-network
    depends_on:
      - otel-collector
    # deploy: # Example for future GPU resources
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
    networks:
      - zebra-network

  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "16686:16686" # Jaeger UI
    networks:
      - zebra-network

networks:
  zebra-network:
    driver: bridge