name: CI

on: [push, pull_request]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: zebra
          POSTGRES_PASSWORD: zebra
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U zebra" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install base deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Lint & Typecheck
        run: |
          pip install black ruff mypy
          ruff .
          black --check .
          mypy src || true
      - name: Run tests
        run: |
          pip install pytest
          pytest -q
      - name: Build docker images
        run: |
          docker compose -f docker-compose.yml build --parallel